package com.smplkit.config;

import java.util.Map;
import java.util.Objects;

/**
 * Parameters for creating a new configuration.
 *
 * <p>Use the {@link #builder(String)} factory method to obtain a builder:</p>
 * <pre>{@code
 * CreateConfigParams params = CreateConfigParams.builder("My Config")
 *     .key("my_config")
 *     .description("A description")
 *     .values(Map.of("timeout", 30))
 *     .build();
 * }</pre>
 */
public final class CreateConfigParams {

    private final String name;
    private final String key;
    private final String description;
    private final String parent;
    private final Map<String, Object> values;

    private CreateConfigParams(Builder builder) {
        this.name = builder.name;
        this.key = builder.key;
        this.description = builder.description;
        this.parent = builder.parent;
        this.values = builder.values;
    }

    /** Returns the display name. */
    public String name() { return name; }

    /** Returns the human-readable key, or null if auto-generated. */
    public String key() { return key; }

    /** Returns the optional description, or null. */
    public String description() { return description; }

    /** Returns the parent config UUID, or null. */
    public String parent() { return parent; }

    /** Returns the initial base values, or null. */
    public Map<String, Object> values() { return values; }

    /**
     * Creates a new builder with the required name parameter.
     *
     * @param name display name for the config
     * @return a new builder
     */
    public static Builder builder(String name) {
        return new Builder(name);
    }

    /**
     * Builder for {@link CreateConfigParams}.
     */
    public static final class Builder {

        private final String name;
        private String key;
        private String description;
        private String parent;
        private Map<String, Object> values;

        private Builder(String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
        }

        /**
         * Sets the human-readable key. Auto-generated by the server if omitted.
         *
         * @param key the config key
         * @return this builder
         */
        public Builder key(String key) {
            this.key = key;
            return this;
        }

        /**
         * Sets an optional description.
         *
         * @param description the description
         * @return this builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Sets the parent config UUID.
         *
         * @param parent the parent UUID
         * @return this builder
         */
        public Builder parent(String parent) {
            this.parent = parent;
            return this;
        }

        /**
         * Sets the initial base values.
         *
         * @param values the values map
         * @return this builder
         */
        public Builder values(Map<String, Object> values) {
            this.values = values;
            return this;
        }

        /**
         * Builds the {@link CreateConfigParams} instance.
         *
         * @return the params
         */
        public CreateConfigParams build() {
            return new CreateConfigParams(this);
        }
    }
}
